### PR TITLE
Changed buildstep so the main bower file gets ng-annotated also

### PR DESCRIPTION
**Pull request by mbrand**
Hi!

We were having problems with your bower config because your main file declared in the bower.json didn't have annotations. Alot of build tools depend on these main file declarations and minify those.
I changed your buildstep to put the build into a dist/ folder and adjusted the bower.json accordingly.
Would love to see a new version of this :).

### CODE REVIEW

**Comment by jameskleeh** [comment]
@mbrand Do you use `ngAnnotate` as part of your build process?

**Comment by mbrand** [comment]
@Schlogen Yes I do. But I really only do it for my own files and not for libs, as I think that libs should run "out of the box".

**Comment by jameskleeh** [comment]
@mbrand Thanks for the reply. The minified version will run "out of the box". What prevents you from using that?

**Comment by mishupetre** [comment]
First of all, thanks for maintaining this package, @Schlogen. Encountered the same problem here. I like to use full lib version when developing and minify it in the build process when deploying to a server, so I'd like to see @mbrand's suggestion implemented as well.

**Comment by mbrand** [comment]
@Schlogen Build tools like https://github.com/jonkemp/gulp-useref are relying on the lib file specified as main. You can overwrite this behavior of course, but in my opinion the file that's specified as main should simply run out of the box, even if it's used in a minified build. I think a consumer of a Libraray shouldn't need any additional steps to make it run either minified or not.

**Comment by katagaStyle** [comment]
Same issue here. 
@mbrand++

**Comment by jameskleeh** [comment]
I'm closing this PR as it is a breaking change to move where the files are located. Instead due to the amount of requests I've received about it, even though I disagree, I've annotated the non minified file version 1.2.5.

**Pull request closed without merging**
