### PR TITLE
Text Message extension

### PR DESCRIPTION
**Pull request by akka81**
it's now possible to see a text area inside the confirm-modal and get the text written back into the caller scope; just add a confirmMessage attribute to the button or not if you want the standard behavior.

### CODE REVIEW

**Comment by jameskleeh** [comment]
Please revert changes to the minified files version as it is built automatically.

**Comment by akka81** [comment]
OK l'll remove the file, but i'm in trouble with the last two tests cause
i'm not able to pass to confirm call the directive scope which is part of
my change, can you help me?
Il 23 gen 2016 3:19 AM, "James Kleeh" notifications@github.com ha scritto:

**Comment by jameskleeh** [comment]
So I'm a little bit confused on what you are trying to accomplish with the PR. Based on what I've seen, this doesn't seem like something people would want by default. Can you tell me why this should be the default for everyone?

**Comment by akka81** [comment]
The default behavoir is not changed, if you want the textarea you have to
use the confirmMessage attribute otherwise the modal will render normally.
It can be usefull for example when you use the confirm dialog inside
workflow steps or to justify a particular action in some kind of application
Il 23 gen 2016 22:23, "James Kleeh" notifications@github.com ha scritto:

**Comment by jameskleeh** [comment]
@akka81 I truly appreciate your submission, however I'm not convinced this feature is something a large percentage of users would use. I think it is important to not add too many parameters/edge cases to a common module like this to keep it easy to use and easy to learn. Thanks again for the effort you put into this. I hope this doesn't discourage you from doing so in the future. My suggestion for the future is to open an issue to discuss the idea before submitting a PR. I think that's good practice for all open source projects.

**Pull request closed without merging**
