### PR TITLE
Add dependency injection

### PR DESCRIPTION
**Pull request by vbyno**
Guys, I had problems using { strictDi: true } so I added dependency injection to functions.
Also I had errors as far as there were no template files. So I required whole 'ui.bootstrap' module instead of just ui.bootstrap.modal. (as was advised [here](https://github.com/angular-ui/bootstrap/wiki/FAQ#full-explanation).
Suggestions are welcomed. Hope you'll find these changes valuable

### CODE REVIEW

**Comment by simison** [comment]
Hmm, interesting dilemma. I was also considering turning `strictDi: true` for @Trustroots.

> So I required whole 'ui.bootstrap' module instead of just ui.bootstrap.modal

This wouldn't work in my case, since I'm custom-building ui.bootstrap to avoid having so much not-needed JS. It should work if you also inject template modules, right?

**Comment by vbyno** [comment]
@simison

> It should work if you also inject template modules, right?

Yep, it works after adding
`angular.module('angular-confirm', ['ui.bootstrap.modal', 'uib/template/modal/window.html', 'uib/template/modal/backdrop.html'])` to [this line](https://github.com/Schlogen/angular-confirm/pull/51/commits/6c519eb4b241b84e86e3c5aa1eb75ff73aa309a7#diff-7867170affc1a11362b2a86808b7108bR17)
Would that implementation be more appropriate?

**Comment by vbyno** [comment]
So, I left it as it was with `ui.bootstrap.modal`and just added dependency injection. Now it should just fix [this issue](https://github.com/Schlogen/angular-confirm/issues/52)

**Comment by jameskleeh** [comment]
The injection stuff happens automatically when creating the minified version. If you don't have a process in place for that to happen with your build, I recommend using the minified version.

`.controller("ConfirmModalController",["$scope","$uibModalInstance","data",function(e,t,i)`

**Comment by vbyno** [comment]
I wouldn't agree with that. Minified version is bad for debugging in development mode. Even [ui-bootstrap](https://github.com/angular-ui/bootstrap/blob/gh-pages/ui-bootstrap-1.3.1.js) which you use adds injection to the main version not only for minified.

**Comment by jameskleeh** [comment]
@vbyno I would recommend adding an `ng-annotate` step to your build so you can have the best of both worlds.

**Pull request closed without merging**
